### ISSUE TITLE
Pipes wont appear.

### ISSUE THREAD

**Issue by penneShells** [techwithtim/NEAT-Flappy-Bird#13]
I have finished the tutorial but keep getting the error message,

AttributeError: 'str' object has no attribute 'stagnation_type'

which says it occurs in the file

File "/usr/local/lib/python3.7/dist-packages/neat/population.py

Any help on why this might happen would be great!

**Comment by LucasColas** [comment]
Where does this error come form in your code ? Which lines ?

**Comment by penneShells** [comment]
This is the full error message:

Traceback (most recent call last):
  File "/home/pi/Documents/flappyBirdAi.py", line 275, in <module>
    run(config_path)
  File "/home/pi/Documents/flappyBirdAi.py", line 264, in run
    p = neat.Population(config_path)
  File "/usr/local/lib/python3.7/dist-packages/neat/population.py", line 26, in __init__
    stagnation = config.stagnation_type(config.stagnation_config, self.reporters)
AttributeError: 'str' object has no attribute 'stagnation_type'

**Comment by penneShells** [comment]
I just changed something after i realised a typo in a different line and i no longer get an error message, but pipes dont spawn, and after a few birds die to the floor and ceiling, all birds instantly die and a new generation begins.

**Comment by penneShells** [comment]
After a few generations they stop dying and keep steadily jumping. Pipes no longer spawn. I suppose on the bright side the ai part worked.
