### ISSUE TITLE
   AttributeError: 

### ISSUE THREAD

**Issue by patelaarav** [techwithtim/NEAT-Flappy-Bird#14]
WIDTH = BASE_IMG.get_width()
AttributeError: 'list' object has no attribute 'get_width

**Comment by LucasColas** [comment]
You try to use a method "get_width()" this method is probably from Pygame. If it's from pygame, this method must be used for a surface, not a list. Indeed this method gets the width of the Surface. It returns the width of the Surface in pixels.

**Comment by patelaarav** [comment]
pipe.draw(win) 
AttributeError: 'Pipe' object has no attribute 'draw'
