### ISSUE TITLE
module neat has no attribute config

### ISSUE THREAD

**Issue by AnkithAbhayan** [techwithtim/NEAT-Flappy-Bird#19]
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Matplotlib is building the font cache; this may take a moment.
Traceback (most recent call last):
  File "flappy_bird.py", line 441, in <module>
    run(config_path)
  File "flappy_bird.py", line 415, in run
    config = neat.config.Config(neat.DefaultGenome, neat.DefaultReproduction,
AttributeError: module 'neat' has no attribute 'config'

**Comment by carmonkeylab** [comment]
try uninstalling neat and reinstalling, that is what i did to solve my problem

**Comment by iamjiamingliu** [comment]
Ayyy the real cause of this phenomenon, as Tim as described in his video tutorial, is that we should use pip to install "neat-python", not just "neat".
Basically, type "pip install neat-python", and the issue should be solved :)

**Comment by AnkithAbhayan** [comment]
I'll try that, thankyou
