### ISSUE TITLE
pygame.error: Couldn't open imgs\pipe.png  (imgs folder is still there) python 3.7.6

### ISSUE THREAD

**Issue by ghost** [techwithtim/NEAT-Flappy-Bird#20]
ts/NEAT-Flappy-Bird/flappy_bird.py
pygame 2.0.0.dev6 (SDL 2.0.10, python 3.7.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "c:/Users/osty2/Documents/programing_projects/NEAT-Flappy-Bird/flappy_bird.py", line 28, in <module>
    pipe_img = pygame.transform.scale2x(pygame.image.load(os.path.join("imgs","pipe.png")).convert_alpha())
pygame.error: Couldn't open imgs\pipe.png
PS C:\Users\osty2\Documents\programing_projects> 

VScode - direct clone.

![Screenshot (342)](https://user-images.githubusercontent.com/56374185/95665858-21469700-0b22-11eb-9652-bbf2ac2ae523.png)
![Screenshot (343)](https://user-images.githubusercontent.com/56374185/95665859-21df2d80-0b22-11eb-9d93-bf625b0e3c20.png)

**Comment by ghost** [comment]
i'm a relatively new programer (i've only done this for a year) so im happy to take any criticism and i understand that i might have done something stupid and its most likely my fault. good luck i guess.

**Comment by ghost** [comment]
Update: doesn't work in 3.8

**Comment by Aryankpoor** [comment]
It is working in **_3.8.6_** and **_3.9_** for me 
specs:  windows 10 and vscode - version 1.47
There is no error showing like that for me, the game is working just fine

**Comment by Aryankpoor** [comment]
Btw I also checked it on repl.it and it works there also just fine, 
![Capture](https://user-images.githubusercontent.com/64773763/95852621-abd10580-0d71-11eb-8be4-c3a67326a556.JPG)

**Comment by ghost** [comment]
well im windows 10 vs code and python 3.8.6 but that wasn't the problem. i was running it from a folder and it was trying to pull  from the base there instead of the file for this. the repl link works but its very slow so im looking to run it locally.

**Comment by ghost** [comment]
the new issue im having is the same as [here](https://github.com/rsk2327/NEAT_FlappyBird/issues/2) (none of the solutions work for me) im trying other things and looking for more sources but any help is apreciated.

**Comment by ghost** [comment]
fixed it, use command `pip install neat-python==0.9` (windows cmd)

**Comment by Aryankpoor** [comment]
> well im windows 10 vs code and python 3.8.6 but that wasn't the problem. i was running it from a folder and it was trying to pull from the base there instead of the file for this. the repl link works but its very slow so im looking to run it locally.

Yeah in repl.it the game was very-very slow

**Comment by ghost** [comment]
by the way how do you get the output of this to be in a terminal? like the gen statistics?

**Comment by Aryankpoor** [comment]
That is not the terminal , that is reply.it, and btw just for info I do not use terminal, I run it in interactive python when I use vscode, it is better that way you know

**Comment by ghost** [comment]
like jupiter notebook? i guess for testing but not writing.

**Comment by anuragvalechha** [comment]
i m having the same error help me to fix it
