### ISSUE TITLE
no visualize in neat anymore

### ISSUE THREAD

**Issue by ghost** [techwithtim/NEAT-Flappy-Bird#3]
Hi, i believe that NEAT doesn,t have a visualize module anymore in it, does someone know where i can download that?
this is the error
  File "/Users/m/PycharmProjects/FlappyBirdML/Flappy2?.py", line 13, in <module>
    import visualize
ModuleNotFoundError: No module named 'visualize'

**Comment by techwithtim** [comment]
You need to clone the entire repository, you’ll notice there is a module called visualize in there. You’re correct, there is no pip package for visualize. The visualize.py file contains some classes that used the graphviz module to display information. 

Thanks,
Tim
