### ISSUE TITLE
config

### ISSUE THREAD

**Issue by ghost** [techwithtim/NEAT-Flappy-Bird#4]
for some reason i keep getting this error. 

`/Users/banginpadr/Desktop/coders/ai/venv/bin/python /Users/banginpadr/Desktop/coders/ai/neuton.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/Users/banginpadr/Desktop/coders/ai/neuton.py", line 440, in <module>
    run(config_path)
  File "/Users/banginpadr/Desktop/coders/ai/neuton.py", line 414, in run
    config = neat.config.Config(neat.DefaultGenome, neat.DefaultReproduction,
AttributeError: module 'neat' has no attribute config`

**Comment by techwithtim** [comment]
Thanks,
Tim

**Comment by techwithtim** [comment]
Make sure you don’t have a python file named “neat.py” in your directory.

Thanks,
Tim
